package formatter

const INDENTATION = "\t"
const TEMPLATE_VARIABLE_OPENING_TAG = "___TEMPLATE_VARIABLE_OPENING_TAG___"
const TEMPLATE_VARIABLE_CLOSING_TAG = "___TEMPLATE_VARIABLE_CLOSING_TAG___"
const TEMPLATE_BRACKET_OPENING_TAG = "___TEMPLATE_BRACKET_OPENING_TAG___"
const TEMPLATE_BRACKET_CLOSING_TAG = "___TEMPLATE_BRACKET_CLOSING_TAG___"
